# Generated by Django 5.1.2 on 2025-02-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=25)),
                ('Number', models.IntegerField(max_length=12)),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
    ]
