# Generated by Django 5.1.2 on 2025-02-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='Number',
            field=models.IntegerField(max_length=15),
        ),
    ]
