# Generated by Django 5.1.6 on 2025-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_portfolio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Number',
            field=models.BigIntegerField(),
        ),
    ]
