# Generated by Django 5.1.6 on 2025-02-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_portfolio_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='Number',
            new_name='number',
        ),
    ]
